apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: devops-mongo
spec:
  type: ClusterIP
  selector:
    app: mongo-express
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
