apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 1  # Start with 1 pod; can be scaled later
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4  # Official Apache2 image
        ports:
        - containerPort: 80  # Apache listens on port 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: apache
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080  # Optional: Specify a fixed port between 30000-32767
  type: NodePort  # Exposes the service on each node's IP at the nodePort
