FROM openjdk:11-jdk-slim
RUN apt-get update && apt-get install -y maven && rm -rf /var/lib/apt/lists/*
RUN useradd -m -d /home/jenkins -s /bin/bash jenkins
USER jenkins
WORKDIR /home/jenkins
ENTRYPOINT ["java", "-jar", "/agent.jar"]