pipeline {
  agent none
  options { skipDefaultCheckout(true) }

  stages {
    stage('Checkout') {
      agent { label 'linux1' }   // do initial checkout on agent1
      steps {
        checkout scm
        stash name: 'src', includes: '**/*'
      }
    }

    stage('Compile on agent1') {
      agent { label 'linux1' }
      steps {
        unstash 'src'
        sh 'mvn -B -DskipTests clean package'
        stash name: 'built', includes: 'target/**/*, pom.xml'
      }
    }

    stage('Test on agent2') {
      agent { label 'linux2' }
      steps {
        unstash 'src'   // bring source (and pom) to agent2
        sh 'mvn -B test'
        junit 'target/surefire-reports/*.xml'
      }
    }
  }

  post {
    always {
      echo "Build finished on distributed agents."
    }
  }
}
